FROM python:3.10
WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
EXPOSE 8000

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV DJANGO_SETTINGS_MODULE=backend.settings

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]